# Generated by Django 3.2 on 2021-08-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название объявления')),
                ('city', models.CharField(choices=[('1', 'Москва'), ('2', 'Санкт-Петербург'), ('3', 'Екатеринбург'), ('4', 'Владивосток'), ('5', 'Владимир')], max_length=1, verbose_name='Город')),
                ('geolocation', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_person', models.IntegerField(verbose_name='Количество человек')),
                ('number_of_girls', models.IntegerField(verbose_name='Количество девушек')),
                ('number_of_boys', models.IntegerField(verbose_name='Количество парней')),
                ('party_date', models.DateTimeField(verbose_name='Дата вечеринки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('create_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
