# Generated by Django 3.2 on 2021-08-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чатов',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ImageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(blank=True, upload_to='chat/first_image/%Y/%m/%d', verbose_name='Первое фотография')),
                ('second_image', models.ImageField(blank=True, upload_to='chat/second_image/%Y/%m/%d', verbose_name='Вторая фотография')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Комната чата',
                'verbose_name_plural': 'Комнаты чатов',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Голосования',
                'verbose_name_plural': 'Голосовании',
            },
        ),
    ]
